# Generated by Django 4.2.1 on 2023-06-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='olddojo', max_length=255),
            preserve_default=False,
        ),
    ]
